# Generated by Django 4.2.4 on 2023-08-17 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='complete_before',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Закончить до'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Завершено'),
        ),
    ]
