name: Sync branches after tests
on:
  workflow_run:
    workflows: [Run tests]
    branches: [dev]
    types:
      - completed

jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge dev -> main
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: dev
          target_branch: main
          github_token: ${{ secrets.SECRET_TOKEN }}